[muxcable] Remove Xcvrd Sleep
Azure/sonic-platform-daemons pull request #174
Opened 2021-04-21 19:06 UTC by tahmed-dev

#### Description

When using redis select, xcvrd is sleeping for 100msec which appears
unnecessary after process all content of selectable objects.

signed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>

#### Motivation and Context
Reduce overall time it takes to switch multiple/all ports

#### How Has This Been Tested?
Test on test cluster where 24 ports were switched and saw 100msec~200msec gain in switching time of all ports. Individual port switch time is still within 20msec~30msec.

#### Additional Information (Optional)

2021-04-21 19:20 UTC, jleveque requested changes
Please fix LGTM alert (no longer `import time`)

2021-04-21 19:24 UTC, jleveque commented
Has the sonic-swss-common submodule been updated to include the threading fix? If not, this PR should wait until then.

2021-04-21 21:12 UTC, tahmed-dev commented
> Has the sonic-swss-common submodule been updated to include the threading fix? If not, this PR should wait until then.

test without `swss-common` threading fix and saw the gain mentioned in the description of this PR.

2021-04-21 22:05 UTC, vdahiya12 commented
last i checked main xcvrd thread stopped running as I could not see TRANSCEIVER_INFO table getting any updates, if i removed the sleep.

2021-04-21 23:24 UTC, tahmed-dev commented
> last i checked main xcvrd thread stopped running as I could not see TRANSCEIVER_INFO table getting any updates, if i removed the sleep.

can you please try with the recent changes?

2021-04-21 23:33 UTC, jleveque commented
I think we should wait for the sonic-swss-common submodule update. The threading issue is properly fixed upstream.

2021-05-10 20:32 UTC, vdahiya12 approved these changes

2021-05-11 00:26 UTC, tahmed-dev commented
> Has the sonic-swss-common submodule been updated to include the threading fix? If not, this PR should wait until then.

@jleveque can you please unblock this PR?

2021-05-11 00:34 UTC, jleveque approved these changes

2021-05-11 02:22 UTC, tahmed-dev commented
> Please fix LGTM alert (no longer `import time`)

@jleveque  There are requested changes that are blocking the merge of this PR.

2021-05-11 02:24 UTC, merged