[xcvrd] Enhance Media Settings
Azure/sonic-platform-daemons pull request #177
Opened 2021-04-27 14:02 UTC by aravindmani-1

#### Description
1. Currently in sonic, for 400G pre-emphasis settings is not programmed via common methodology. 
We use Vendor Name + PN to program which would consume memory and never ending process as we need to add Vendor name + PN for every optic.
2.  For 100G/40G optics, specification compliance is not displayed. Only for DAC, the specification compliance was displayed.
#### Motivation and Context

1. With this PR, we can program the pre-emphasis settings for both DAC,AOC and optics.
QSFP_DD parser doesn't have specification compliance which was need to program pre-emphasis settings.
The platform API code can be changed to return the type_of_media_interface for 400G media specification compliance, so that the type of media can be determined.
     https://github.com/Azure/sonic-platform-common/blob/a95834b65a9f3b17ab1ce4e1ba5d1a60102e4507/sonic_platform_base/sonic_sfp/sff8024.py#L104
2. To address 100G/40G optic, introduced a new key "QSFP28 - *" / "QSFP+ - *" (type_abbrv_name followed by an hyphen) .
The same key has to be defined in vendor specific media_settings.json. 
This change doesn't change the existing behavior but additionally addresses the above mentioned issues.
Vendors can still add "Vendor_name + PN" in media_settings.json to program media settings if needed.

#### How Has This Been Tested?

- Stop and start pmon docker with updated media_settings and check the values are displayed in APP_DB.
- Verify the syslogs and make sure that it doesn't throw any error.
UT:
[xcvrd_media_settings_UT.txt](https://github.com/Azure/sonic-platform-daemons/files/6385110/xcvrd_media_settings_UT.txt)

#### Additional Information (Optional)

2021-04-27 14:12 UTC, aravindmani-1 commented
@jleveque , @daall Can you please review the changes?.

2021-04-27 16:47 UTC, jleveque requested changes

2021-04-27 16:47 UTC, jleveque commented on sonic-xcvrd/xcvrd/xcvrd.py
> +            helper_logger.log_error("Error in obtaining media setting for",logical_port_name)
Add space after comma

2021-04-28 17:12 UTC, jleveque requested changes

2021-04-28 17:12 UTC, jleveque commented on sonic-xcvrd/xcvrd/xcvrd.py
> +            helper_logger.log_error("Error in obtaining media setting for", logical_port_name)
Is this syntax tested with this function? I prefer passing one string:

```python
helper_logger.log_error("Error in obtaining media setting for {}".format(logical_port_name))
```

2021-04-28 17:46 UTC, jleveque approved these changes

2021-04-28 17:47 UTC, merged