[chassisd] Add script to initialize chassis info in STATE_DB
Azure/sonic-platform-daemons pull request #183
Opened 2021-05-12 18:47 UTC by robocoder99

#### Description
I added a new script `chassisshow` that uploads chassis hardware information such as serial number, model number and hardware revision to the STATE_DB under the CHASSIS_INFO table. 

#### Motivation and Context
I made this change in order to expose the chassis hardware information to SONiC user space and allow CLI utilities to access it in order to expose it to the user. 

#### How Has This Been Tested?
Unit tests were added and was deployed and tested on Mellanox platform MSN2700.

2021-05-12 19:52 UTC, jleveque requested changes

2021-05-12 19:52 UTC, jleveque commented on sonic-chassisd/tests/test_chassis_db_init.py
> +
Delete trailing blank lines

2021-05-12 19:54 UTC, jleveque commented
Also please update PR description, as it references `chassisshow`, which is not part of this PR.

2021-05-12 20:54 UTC, jleveque commented
Just curious why a separate script is necessary for this. Why can we not simply add this logic to chassisd when it starts up?

2021-05-12 20:58 UTC, robocoder99 commented
We decided on a separate script because chassisd is primarily for handling modular chassis management (and thus is only run on modular chassis platforms), a separate task from uploading basic information such as serial, model, and hardware revision that is applicable to all platforms and also one-shot.

2021-05-12 23:38 UTC, jleveque approved these changes

2021-05-18 01:39 UTC, jleveque commented
Since this script is a one-shot script, and not a daemon per se, I have reservations about adding it in this repo. We could simply add it in the buildimage repo as part of https://github.com/Azure/sonic-buildimage/pull/7596. However, it would not be built into a package, so we would not be able to run unit tests against it. I'm on the fence, but I guess I can live with having it as part of the chassisd package.

2021-05-18 15:46 UTC, robocoder99 commented
I would argue that while the name `sonic-platform-daemons` does indicate a one-shot task wouldn't belong, architecturally it does belong here as it performs the same fundamental task as the chassisd daemon (uploading chassis information to the redis db). As such anyone looking for this code would likely expect to find it here and I think that is valuable. 

If there exists now or in the future a collection of one-shot tasks for the purpose of provisioning redis then I would argue this should be refactored at that point.

2021-05-18 16:18 UTC, jleveque commented
> architecturally it does belong here as it performs the same fundamental task as the chassisd daemon (uploading chassis information to the redis db).

I agree with this, which is why I am on the fence.

> If there exists now or in the future a collection of one-shot tasks for the purpose of provisioning redis then I would argue this should be refactored at that point.

Agreed. We can proceed with this PR.

2021-05-18 16:18 UTC, merged