[python coverage]fix result color bar
Azure/sonic-platform-daemons pull request #196
Opened 2021-06-23 06:20 UTC by pettershao-ragilenetworks

What I did
fix python gcov warning "Please install dotnet core to enable automatic generation of Html report"
more info check: Azure/sonic-snmpagent#215
How I did it
install dotnet core
How to verify it

2021-06-23 06:46 UTC, pettershao-ragilenetworks commented
@xumia @lguohan hi , help forward, thanks!

2021-06-25 23:43 UTC, jleveque requested changes

2021-06-25 23:43 UTC, jleveque commented on azure-pipelines.yml
> +          sudo dpkg -i packages-microsoft-prod.deb
Why download this package? Can you not simply use `apt-add-repository` as demonstrated in the "Ubuntu 20.04 (Focal)" section here: https://docs.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software.

2021-07-01 19:53 UTC, lguohan commented on azure-pipelines.yml
> +          sudo apt-get -y install -f
do we still need this command?

2021-07-08 04:21 UTC, pettershao-ragilenetworks commented on azure-pipelines.yml
> +          sudo apt-get -y install -f
fixed, help forward!

2021-07-08 17:29 UTC, lguohan approved these changes

2021-07-08 17:29 UTC, merged